# Generated by Django 5.0.6 on 2025-01-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0009_remove_csedata_location_remove_csedata_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscustomuser',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
    ]
