# Generated by Django 5.0.6 on 2025-01-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0011_alter_studentscustomuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscustomuser',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
