# Generated by Django 5.0.6 on 2025-01-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0012_alter_studentscustomuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='csedata',
            name='isPresent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ecedata',
            name='isPresent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itdata',
            name='isPresent',
            field=models.BooleanField(default=True),
        ),
    ]
