# Generated by Django 5.0.6 on 2025-01-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0013_csedata_ispresent_ecedata_ispresent_itdata_ispresent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscustomuser',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentscustomuser',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
